name: rusty_river_project
description: SE494 group project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adv_fab: ^1.0.5
  http: ^0.13.4
  provider: ^6.0.2
  url_launcher: ^6.0.18
  custom_navigation_bar: ^0.8.2
  flutter_swiper_plus: ^2.0.4
  flutter_smart_dialog: ^3.3.7
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: "assets/fonts/Roboto-Regular.ttf"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/bacteria.png"