name: rusty_river_project
description: SE494 group project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adv_fab: ^1.0.5
  http: ^0.13.4
  provider: ^6.0.2
  go_router: ^3.0.1
  custom_navigation_bar: ^0.8.2
  animated_fab_button_menu: ^0.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_smart_dialog: ^3.3.1
  flutter_animated_dialog: ^2.0.1
  flutter_swiper: ^1.1.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/images/wildlife.png"